version: '3'
services:
  eureka-server:
    image: wisdom/eureka-server:latest
    container_name: eureka-server
    restart: always
    hostname: eureka-server
    ports:
      - 8761:8761

  service:
    image: wisdom/service:latest
    container_name: service
    restart: always
    ports:
      - 9090:9090

  v2-api:
    image: wisdom/v2-api:latest
    container_name: v2-api
    restart: always
    ports:
      - 8081:8081

  v2-web:
    image: wisdom/v2-web:latest
    container_name: v2-web
    restart: always
    ports:
      - 8082:8082

  gateway:
    image: wisdom/gateway:latest
    container_name: gateway
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: dockerelk_elk
