server:
  port: 8082

spring:
  application:
    name: v2-web

feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  config: classpath:logback-spring.xml