server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: eureka-server
