server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server
logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN